### ISSUE TITLE
Issues with joining BG queue

### ISSUE THREAD

**Issue by jimsjoh** [Paojy/Altz-UI#10]
Unable to join Battleground queue, also unable to leave arena queue.

1x [ADDON_ACTION_FORBIDDEN] AddOn 'AltzUIConfig' tried to call the protected function 'JoinBattlefield()'.
!BugGrabber\BugGrabber.lua:573: in function <!BugGrabber\BugGrabber.lua:573>
[C]: in function `JoinBattlefield'
Blizzard_PVPUI\Blizzard_PVPUI-1.0.lua:551: in function`HonorFrame_Queue'
[string "_:OnClick"]:2: in function <[string "_:OnClick"]:1>

**Comment by gear4s** [comment]
@jimsjoh I've fixed it and submitted a pull request here => https://github.com/Paojy/Altz-UI/pull/27
