### ISSUE TITLE
Xperience Bar Issue

### ISSUE THREAD

**Issue by alapasset** [Paojy/Altz-UI#11]
Hello,

First thank you for your job.
Since the last update, when I do an action that gives me experience or connection, I have the error lua:

`
Message: Interface\AddOns\AltzUI\mods\panels\panels.lua:765: attempt to call local 'min' (a number value)
Time: 11/15/16 18:28:27
Count: 5
Stack: Interface\AddOns\AltzUI\mods\panels\panels.lua:765: in function <Interface\AddOns\AltzUI\mods\panels\panels.lua:751>

Locals: self = AltzUI_ExperienceBar {
 0 = <userdata>
 border = <unnamed> {
 }
}
event = "PLAYER_LOGIN"
arg1 = nil
artifactItemID = nil
_ = nil
_ = nil
_ = nil
artifactTotalXP = nil
artifactPointsSpent = nil
_ = nil
_ = nil
_ = nil
_ = nil
_ = nil
_ = nil
artifactMaxed = nil
name = nil
reaction = 0
min = 0
max = 0
value = 0
factionID = 0
newLevel = 108
showArtifact = nil
showXPorRep = true
XP = 432024
maxXP = 705000
name = nil
rank = 0
minRep = 0
maxRep = 0
value = 0
(*temporary) = <function> defined =[C]:-1
(*temporary) = AltzUI_ExperienceBar {
 0 = <userdata>
 border = <unnamed> {
 }
}
(*temporary) = 0
(*temporary) = 0
(*temporary) = 432024
(*temporary) = "attempt to call local 'min' (a number value)"
xpbar = AltzUI_ExperienceBar {
 0 = <userdata>
 border = <unnamed> {
 }
}
artifactbar = AltzUI_ArtifactExperienceBar {
 0 = <userdata>
 border = <unnamed> {
 }
}
`

Thx :)

**Comment by Nazgulup** [comment]
Hi,

I have same issue. I just went to AltzUI\mods\panels\panels.lua line 765. Changed min(0, XP) to 0. And this error doesn't popup again. I don't know if it is correct way to fix it. But right now there  is  no more error.
