### ISSUE TITLE
Impossible to queue for random battlegrounds

### ISSUE THREAD

**Issue by AGachet** [Paojy/Altz-UI#17]
It's seems that a bug happen when I try to join a random BG. I've read here (http://www.wowinterface.com/downloads/info21263-AltzUIforLegion.html#comments) that I'm not alone to have this issue.

I've found any UI as good as this one, and it's boring to be obliged to disabled it each time I want to make a bg. I've reset my setup tons of times to know if it's from me or from the UI setup but I'have always the same issue :/

Could you take a look pls?

**Comment by tbass0814** [comment]
Getting this same issue. I updated aurora and still doesn't allow me to queue for random BGs via the in game menu or a macro. Please fix this. I love your UI but this is making it difficult to play.

**Comment by gear4s** [comment]
I've fixed it and submitted a pull request here => https://github.com/Paojy/Altz-UI/pull/27
