### ISSUE TITLE
Unable to move chat typing box and...

### ISSUE THREAD

**Issue by FulseGaming** [Paojy/Altz-UI#24]
1st off I would like to say I really love the style of the UI and enjoying it alot but I have 2 problems with it:

1st: I really hate that I cant move the chat typing box from the top of the chat window to the bottem of it (a small detail but I find it very unpleasing)

2nd: every time I log in or reload I get this error message:

Message: Interface\AddOns\AltzUIConfig\gui.lua:1635: attempt to index a nil value
Time: 04/13/17 16:50:37
Count: 1
Stack: Interface\AddOns\AltzUIConfig\gui.lua:1635: in function <Interface\AddOns\AltzUIConfig\gui.lua:1624>
Interface\AddOns\AltzUIConfig\gui.lua:1673: in function <Interface\AddOns\AltzUIConfig\gui.lua:1671>
Interface\AddOns\AltzUIConfig\gui.lua:1688: in function <Interface\AddOns\AltzUIConfig\gui.lua:1678>
Interface\AddOns\AltzUIConfig\gui.lua:2280: in function <Interface\AddOns\AltzUIConfig\gui.lua:2280>

Locals: spellID = 6948
parent = AltzUI_itemOptions ScrollAnchor {
 0 = <userdata>
}
list = "item"
bu = AltzUI_caflash_blitem6948 {
 0 = <userdata>
 icon = <unnamed> {
 }
}
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = 18
(*temporary) = <userdata>
(*temporary) = nil
(*temporary) = AltzUI_caflash_blitem6948 {
 0 = <userdata>
 icon = <unnamed> {
 }
}
(*temporary) = "attempt to index a nil value"
G = <table> {
 screenheight = 1080
 media = <table> {
 }
 Ccolors = <table> {
 }
 resolution = "1920x1080"
 BlackList = <table> {
 }
 numFont = "Interface\AddOns\AltzUI\media\number.ttf"
 classcolor = ""
 Client = "enUS"
 Raids = <table> {
 }
 Ccolor = <table> {
 }
 screenwidth = 1920
 uiname = "AltzUI_"
 myClass = "DEATHKNIGHT"
 ClassInfo = <table> {
 }
 Version = "7.19"
 DebuffList = <table> {
 }
 WhiteList = <table> {
 }
 Iconpath = "Interface\AddOns\AltzUI\media\icons\"
 norFont = "Fonts\FRIZQT__.TTF"
}
F = <table> {
 CreateBG = <function> defined @Interface\AddOns\Aurora\aurora.lua:100
 colourArrow = <function> defined @Interface\AddOns\Aurora\aurora.lua:259
 ReskinPortraitFrame = <function> defined @Interface\AddOns\Aurora\aurora.lua:549
 Reskin = <function> defined @Interface\AddOns\Aurora\aurora.lua:149
 ReskinDropDown = <function> defined @Interface\AddOns\Aurora\aurora.lua:272
 dummy = <function> defined @Interface\AddOns\Aurora\aurora.lua:65
 ReskinNavBar = <function> defined @Interface\AddOns\Aurora\aurora.lua:635
 ReskinFilterButton = <function> defined @Interface\AddOns\Aurora\aurora.lua:616
 ReskinIcon = <function> defined @Interface\AddOns\Aurora\aurora.lua:683
 ReskinArrow = <function> defined @Interface\AddOns\Aurora\aurora.lua:404
 AddPlugin = <function> defined @Interface\AddOns\Aurora\aurora.lua:695
 ReskinGarrisonPortrait = <function> defined @Interface\AddOns\Aurora\aurora.lua:656
 colourExpandOrCollapse = <function> defined @Interface\AddOns\Aurora\aurora.lua:498
 CreateBDFrame = <function> defined @Interface\AddOns\Aurora\aurora.lua:580
 CreateSD = <function> defined @Interface\AddOns\Aurora\aurora.lua:77
 clearExpandOrCollapse = <function> defined @Interface\AddOns\Aurora\aurora.lua:505
 clearArrow = <function> defined @Interface\AddOns\Aurora\aurora.lua:265
 ReskinSlider = <function> defined @Interface\AddOns\Aurora\aurora.lua:480
 SetBD = <function> defined @Interface\AddOns\Aurora\aurora.lua:535
 ReskinInput = <function> defined @Interface\AddOns\Aurora\aurora.lua:379
 ReskinClose = <function> defined @Interface\AddOns\Aurora\aurora.lua:332
 ReskinColourSwatch = <function> defined @Interface\AddOns\Aurora\aurora.lua:600
 ReskinRadio = <function> defined @Interface\AddOns\Aurora\aurora.lua:455
 CreateBD = <function> defined @Interface\AddOns\Aurora\aurora.lua:89
 ReskinExpandOrCollapse = <function> defined @Interface\AddOns\Aurora\aurora.lua:513
 ReskinScroll = <function> defined @Interface\AddOns\Aurora\aurora.lua:197
 CreateGradient = <function> defined @Interface\AddOns\Aurora\aurora.lua:117
 ReskinTab = <function> defined @Interface\AddOns\Aurora\aurora.lua:171
 ReskinCheck = <function> defined @Interface\AddOns\Aurora\aurora.lua:423
}
T = <table> {
 createmultilinebox = <function> defined @Interface\AddOns\AltzUIConfig\api.lua:635
 createtext = <function> defined @Interface\AddOns\AltzUIConfig\api.lua:22
 ImportSettings = <function> defined @Interface\AddOns\AltzUIConfig\db.lua:1425
 createnumber = <function> defined @Interface\AddOns\AltzUIConfig\api.lua:29
 Shor

I dont mind the error so much as it isnt happening all the time so 1 quick click on close and it is gone untill the next time I log in or reload but that chat has been driving me up the wall.

Thanks for reading
Fulse.

**Comment by Paojy** [comment]
2 Config→Actionbars→Cooldown Alert
remove all ignored items
