### ISSUE TITLE
Add a license

### ISSUE THREAD

**Issue by angelblue05** [Paojy/Altz-UI#26]
Please add a license to the project. Even if a simple GPLv3.

**Comment by EKE00372** [comment]
will make it later.

**Comment by EKE00372** [comment]
probably need a permission for Aurora.....

**Comment by angelblue05** [comment]
No problem, just let me know here once it is done. Thank you :)

Your skin is the best. Big fan.

**Comment by GergoHex** [comment]
Any update on this?
