### ISSUE TITLE
Vehicle UI doesn't show correctly

### ISSUE THREAD

**Issue by ensey** [Paojy/Altz-UI#28]
When entering a vehicle, the main bar converts to 6 buttons, but it shows the first 6 buttons of actionbar 1 - not the vehicle options.
Therefore, I need to disable AltzUI to complete the quest.

**Comment by ensey** [comment]
Update - it is not constant, it can take a few tries for it to load correctly.
But most of the times, it will show the spells of the normal actionbar, instead of the vehicle spells.

**Comment by gear4s** [comment]
can confirm .. takes a long time for it to work. relogging/reloading doesn't solve
