### ISSUE TITLE
7.03 support?

### ISSUE THREAD

**Issue by JohnWilliams39** [Paojy/Altz-UI#29]
Just curious if this is in the works? :)

**Comment by Paojy** [comment]
works with live version client.

**Comment by angelblue05** [comment]
That's not exactly true.
One thing that was changed is PlaySound. It no longer access string input. You have to provide the SoundKitID. When entering chat, I get an error now.

`: ..\AddOns\AltzUI\mods\chat\playermenu.lua line 48:
   Usage: PlaySound(soundKitID, optional["SFX","Music","Ambience", "Dialog" or "Master"], [forceNoDuplicates, runFinishCallback])
Debug:
   [C]: ?
   [C]: PlaySound()
   AltzUI\mods\chat\playermenu.lua:48:
      AltzUI\mods\chat\playermenu.lua:44`
