### ISSUE TITLE
Bankframe always missing a bag

### ISSUE THREAD

**Issue by angelblue05** [Paojy/Altz-UI#34]
I've done some troubleshooting on your code. I have this issue where the second bank bag does not appear, after the bank is opened the first time. I can reproduce this without fail.

Here's the root of the problem with the code: https://github.com/Paojy/Altz-UI/blob/master/Interface/AddOns/AltzUI/mods/bag/bags.lua#L330-L332
```
frame:SetScript("OnHide", function()
    bank_shown = 0
end)
```
Now if it's possible to know why it triggers when **opening** the bankframe... you know your own code.

**When I first open the bank, here is what I saw:**
It shows the bank, loads every bank bags.
**The second time:**
It shows the bank, loads the first bag (id 5) **then closes the bank**(??), opens the bank again and opens the rest of the bags (id 6+). Because the bank is closed and triggers bank_shown = 0 (onHide event), it resets the number of buttons calculated when processing bags id 6+. Bank bag 5 is then missing.

The code I highlighted is triggering twice. I cannot figure out why but here's what I did to fix the problem. I replaced it with the following:
```
frame:RegisterEvent('BANKFRAME_CLOSED')
frame:SetScript("OnEvent", function(self, event, arg)
    if event == "BANKFRAME_CLOSED" then
        bank_shown = 0
    end
end)
```
Please look into it. I can't be the only one experiencing this. I've reported this issue in the past, but it was never resolved. Thank you 👍

**Comment by Paojy** [comment]
I will look into it. thanks.

**Comment by EKE00372** [comment]
already fixed.
