### ISSUE TITLE
Healer raid frames & click-cast bug

### ISSUE THREAD

**Issue by bnema** [Paojy/Altz-UI#40]
First bug recurrent that I had while leveling is when I enter a dungeon the click-cast is disabled and I have to reload the UI.

Second, when there is a lot a people who join the raid very quickly (like when I am doing a Greater Invasion point) I can right click on the half first part of the raid frames to rejuvenation and the other part it just open the classic right click menu with options to invite etc.

**Comment by Paojy** [comment]
blz forbid initialize click-cast in combat.
