### ISSUE TITLE
Stuttering

### ISSUE THREAD

**Issue by Halovax** [Paojy/Altz-UI#42]
Hey there,

at first, great ui! just loving it. Second, sorry for my worse english. I have a great problem. The game is stuttering with your ui activated. Every 1-2 Seconds there is a framedrop from 60 to 30 for just the wink of a second. I tried it using just your ui as addon and the problem still remains. Tried it with deleting cache, interface and wtf and a fresh reinstall of the ui. The problem still remains. 

Greats

**Comment by EKE00372** [comment]
if you get fps drop with out any addons, it shouldn't be the reason.

**Comment by Halovax** [comment]
Without Addons it runs smooth...sry my english isnt that good. it appears only with your addon running

**Comment by EKE00372** [comment]
we will check it, but altzui not yet for 7.35, paopao still working on it, so not sure what happened you got.

**Comment by Halovax** [comment]
Thx for your help. i´ll wait for the update

**Comment by EKE00372** [comment]
as wowi's comments feedback, turn off Convenient item buttons in config fixed.

try this temporary?

**Comment by EKE00372** [comment]
7.32b on wowi already.
