### ISSUE TITLE
choppy frame when moving

### ISSUE THREAD

**Issue by Urguk** [Paojy/Altz-UI#43]
Seeing choppy frames every 15 secs. This happens when standing still or moving with just Altz-UI load. I have reinstalled WOW deleted my WTF and addons  folder. Just loaded Altz-UI no other UI's installed or loaded. Have latest video drivers Nvidia 1080.  I did load bug grab/stack it did not report any errors. This does not happen in the default game UI. This did not happen until  7.3.5 patch.

**Comment by EKE00372** [comment]
we're looking for this issue but need time.

ty for waiting.

**Comment by EKE00372** [comment]
altzui config > item > common > item level, try disable this

**Comment by Urguk** [comment]
Did the following
altzui config > item > common > item level

Still seeing it.

**Comment by Urguk** [comment]
Update I went in and disable the following

AltUi config > item > common > convenient item button

that fix the choppy frame for me I re-enable the item level,  no issue with
that turned on as of right now.

**Comment by EKE00372** [comment]
hmmm so you still get fps drop when using version 7.32b.

**Comment by Urguk** [comment]
I am just did a fresh install of the UI, disabling the convenient item
button seems to fix the issue.

**Comment by Skrins** [comment]
Hello, 

I confirm that I had the same issue (fps drop every x random seconds), spent one hour playing with WoW and addons settings before narrowing it down to AltZui.

After disabling 

AltUi config > item > common > convenient item button

as stated by Urguk, I confirm it solved the issue for me too.

Best Regards,
ImSo
