### ISSUE TITLE
4 backpack slots from authenticator notification not going away

### ISSUE THREAD

**Issue by nettyneets** [Paojy/Altz-UI#44]
Every time the UI is reloaded, I get the 4x notifications about extra bag slots for adding the authenticator. This doesn't happen with any other bag add on, only with Altz-UI item mods enabled. I have the WoW tutorials disabled and I can't seem to figure out a way to make these go away. As you can see it's really annoying to have to get rid of them each time I log in, as some of them are also hidden behind items. 

![bagbug](https://user-images.githubusercontent.com/7468340/36622637-137f1af0-18f6-11e8-9c21-d02e8022c55d.png)

**Comment by nettyneets** [comment]
Forgot to mention the same thing happens when I open the bank

**Comment by garyyau** [comment]
+1.

**Comment by nettyneets** [comment]
just use Move Anything to move the default bags completely off your screen that way you won't see those messages anymore 👍

**Comment by WoWDumping** [comment]
>
just use Move Anything to move the default bags completely off your screen that way you won't see those messages anymore 
> 

I tried that tonight, got a odd error and had to reset via clearing my configs out of the wtf folder to get altzui bags to work again. I tried different variations. Could you possibly help us out how you do it exactly so it serves the internet better, along with fixing me! :) PLEASE? and thank you!

**Comment by WoWDumping** [comment]
aka this is the ONLY thread on it.
