### ISSUE TITLE
Seeing this odd 1

### ISSUE THREAD

**Issue by Urguk** [Paojy/Altz-UI#48]
Seeing this odd number 1 in yellow next to my action bar or behind it.

**Comment by EKE00372** [comment]
what?

**Comment by Urguk** [comment]
[image: image.png]




[image: image.png]


[image: image.png]

**Comment by Urguk** [comment]
Think is the number for what bar you are on. They may have changed the name
of it looks like it is now part of the MainMenuBarArtFrame.

**Comment by EKE00372** [comment]
emmmm we actually didnt see ur image.......

**Comment by Urguk** [comment]
![unnamed 1](https://user-images.githubusercontent.com/369974/43276448-b410271c-90d2-11e8-9c44-098605d11700.png)
![unnamed 2](https://user-images.githubusercontent.com/369974/43276449-b420cf36-90d2-11e8-8d84-e5fa9e438c79.png)
![unnamed](https://user-images.githubusercontent.com/369974/43276450-b42eb4fc-90d2-11e8-9124-a306305836dc.png)

**Comment by LunaEclipse73** [comment]
I created a pull request for this to make it easier on the addon authors, pull request #54
