### ISSUE TITLE
Unable to move Main Actionbar

### ISSUE THREAD

**Issue by Xellik** [Paojy/Altz-UI#62]
Whenever I try to move the main bar this error pops up:

Message: Interface\AddOns\AltzUI\core\moving.lua:275: attempt to perform arithmetic on local 'x' (a nil value)
Time: Wed Oct  9 08:24:34 2019
Count: 1
Stack: Interface\AddOns\AltzUI\core\moving.lua:275: attempt to perform arithmetic on local 'x' (a nil value)
Interface\AddOns\AltzUI\core\moving.lua:275: in function <Interface\AddOns\AltzUI\core\moving.lua:272>

Locals: self = Altz_Bar1&2DragFrame {
 0 = <userdata>
 mask = <unnamed> {
 }
}
x = nil
y = nil
(*temporary) = <function> defined =[C]:-1
(*temporary) = "%d"
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = "attempt to perform arithmetic on local 'x' (a nil value)"
frame = Altz_Bar1&2 {
 0 = <userdata>
 WrapScript = <function> defined @Interface\FrameXML\SecureHandlers.lua:782
 point = <table> {
 }
 movingname = "Main
Actionbar"
 UnwrapScript = <function> defined @Interface\FrameXML\SecureHandlers.lua:788
 df = Altz_Bar1&2DragFrame {
 }
 SetFrameRef = <function> defined @Interface\FrameXML\SecureHandlers.lua:793
 fadeInfo = <table> {
 }
 eventmode = 1
 Execute = <function> defined @Interface\FrameXML\SecureHandlers.lua:777
}
fname = "Altz_Bar1&2"
role = "dpser"
PlaceCurrentFrame = <function> defined @Interface\AddOns\AltzUI\core\moving.lua:8
DisplayCurrentFramePoint = <function> defined @Interface\AddOns\AltzUI\core\moving.lua:198

**Comment by Paojy** [comment]
fixed
