### ISSUE TITLE
This line shouldn't be there [BarberShopFrame]

### ISSUE THREAD

**Issue by gamer-angel05** [Paojy/Altz-UI#69]
https://github.com/Paojy/Altz-UI/blob/1650f213b87cf88c4f8355835c618140bfc95ca6/Interface/AddOns/AltzUI/mods/tweaks/dragemall.lua#L63

I'm guessing, with the new barber shop options, this line should be removed as it is now a fullscreen frame with a faded background that you shouldn't be able to drag.

**Comment by EKE00372** [comment]
just because paopao forget to delete it
i've told her
too busy

**Comment by gamer-angel05** [comment]
Resolved with 9.07
