### ISSUE TITLE
[Request] Quest-indicator on nameplates

### ISSUE THREAD

**Issue by deadlydag** [Paojy/Altz-UI#75]
I got a request if its possible to implement;

An indicator on nameplates when the mob is a part of a quest.
Any chance this could be added?

'!', or '5/10' (if 10 mobs of that kind are for a quest).
Similar to NDui.

**Comment by deadlydag** [comment]
Another request:
Mouse tooltip-anchor.

**Comment by Paojy** [comment]
added in 10.06
